CREATE TABLE IF NOT EXISTS commands (
    uid         INTEGER PRIMARY KEY AUTOINCREMENT,
    command_id 	INTEGER NOT NULL,
    command 	TEXT,
    status 		INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS agents (
    uid         INTEGER PRIMARY KEY AUTOINCREMENT,
    name 		TEXT NOT NULL UNIQUE
);